framework:
    translator: { fallbacks: ["%locale%"] }
    secret: '%env(APP_SECRET)%'
    form: true
    csrf_protection: true
    session:
        handler_id: ~
        storage_factory_id: session.storage.factory.native
    serializer:
        mapping:
            paths: [ '%kernel.project_dir%/config/serialization', '%kernel.project_dir%/src/Component/Core/Api/Resources/serialization' ]
