framework:
    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
        save_path: '%env(REDIS_URL)%'

services:
    Redis:
        class: Redis
        calls:
            - method: connect
              arguments:
                  - '%env(REDIS_HOST)%'
                  - '%env(int:REDIS_PORT)%'

    redis.session_handler:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
        arguments:
            - '@Redis'
            - { prefix: 'session_', ttl: 86400 }

sylius_core:
    filesystem:
        adapter:
            type: aws-s3
            bucket: '%env(SUPABASE_BUCKET)%'
            region: 'us-east-1'
            version: 'latest'
            endpoint: '%env(SUPABASE_URL)%/storage/v1'
            key: '%env(SUPABASE_KEY)%'
            secret: 'dummy'
            options:
                override_endpoint: true 